/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new user
         * @description Creates a new user account and returns a JWT access token.
         */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login with email and password
         * @description Validates credentials and returns a JWT access token.
         */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user profile
         * @description Returns the profile of the currently authenticated user.
         */
        get: operations["UsersController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update current user profile
         * @description Updates name and/or email of the currently authenticated user.
         */
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all workspaces
         * @description Returns all workspaces owned by the authenticated user.
         */
        get: operations["WorkspacesController_listWorkspaces"];
        put?: never;
        /**
         * Create a new workspace
         * @description Creates a workspace owned by the authenticated user.
         */
        post: operations["WorkspacesController_createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload an asset
         * @description Uploads a file to the specified workspace.
         *
         *     **Deduplication** is applied automatically for images:
         *     - **Exact duplicates** (same SHA-256) → `409 Conflict`
         *     - **Near duplicates** (pHash Hamming distance ≤ 10) → `409 Conflict`
         *
         *     Pass `?force=true` to bypass all deduplication checks and always save the file.
         */
        post: operations["AssetsController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AssetsController_listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AssetsController_deleteAsset"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search assets in a workspace */
        get: operations["SearchController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/admin/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger blue-green reindexing for the current customer */
        post: operations["ReindexController_reindex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search/admin/reindex/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger blue-green reindexing for a specific customer (Admin only) */
        post: operations["ReindexController_reindexCustomer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/metadata/fields": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all metadata field definitions in a workspace */
        get: operations["MetadataFieldsController_findAll"];
        put?: never;
        /** Create a metadata field definition */
        post: operations["MetadataFieldsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/metadata/fields/{fieldId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single metadata field definition */
        get: operations["MetadataFieldsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a metadata field definition */
        delete: operations["MetadataFieldsController_remove"];
        options?: never;
        head?: never;
        /** Update a metadata field definition */
        patch: operations["MetadataFieldsController_update"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/metadata/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all metadata groups in a workspace */
        get: operations["MetadataGroupsController_findAll"];
        put?: never;
        /** Create a metadata group */
        post: operations["MetadataGroupsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/metadata/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a metadata group */
        delete: operations["MetadataGroupsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/metadata/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all metadata templates in a workspace */
        get: operations["MetadataTemplatesController_findAll"];
        put?: never;
        /** Create a metadata template */
        post: operations["MetadataTemplatesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/metadata/templates/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single template */
        get: operations["MetadataTemplatesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a metadata template */
        delete: operations["MetadataTemplatesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all metadata for an asset
         * @description Returns all metadata values with their field definitions.
         */
        get: operations["AssetMetadataController_getMetadata"];
        /**
         * Batch upsert metadata on an asset
         * @description Sets one or more metadata field values. Values are validated against field type and rules. Each update creates a version record.
         */
        put: operations["AssetMetadataController_setMetadata"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}/apply-template/{templateId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a metadata template to an asset
         * @description Adds any template fields not already present on the asset, using their configured default values.
         */
        post: operations["AssetMetadataController_applyTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}/metadata/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Full metadata version history for an asset
         * @description Returns a chronological list of all metadata changes, newest first.
         */
        get: operations["AssetMetadataController_getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}/metadata/history/{fieldId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Version history for a specific metadata field on an asset */
        get: operations["AssetMetadataController_getFieldHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tags in a workspace */
        get: operations["TagsController_listWorkspaceTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/assets/{assetId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all tags on an asset */
        get: operations["TagsController_getAssetTags"];
        put?: never;
        /**
         * Add tags to an asset
         * @description Adds one or more tags. Tags are created if they do not already exist. Names are normalized (lowercase, trimmed).
         */
        post: operations["TagsController_addTags"];
        /**
         * Remove tags from an asset
         * @description Detaches tags — does not delete the tag from the workspace.
         */
        delete: operations["TagsController_removeTags"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}/ai-metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all AI metadata for an asset
         * @description Returns all AI metadata records across all providers, newest first.
         */
        get: operations["AiMetadataController_getForAsset"];
        put?: never;
        /**
         * Ingest AI-generated metadata
         * @description Stores AI metadata from a provider (labels, OCR, colors, scene tags). Each ingestion creates a new record, preserving history.
         */
        post: operations["AiMetadataController_ingest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{assetId}/ai-metadata/{provider}/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get most recent AI metadata from a specific provider */
        get: operations["AiMetadataController_getLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description User email address
             * @example jane@example.com
             */
            email: string;
            /**
             * @description Password (min 8 characters)
             * @example supersecret123
             */
            password: string;
            /**
             * @description Display name
             * @example Jane Doe
             */
            name: string;
            /**
             * @description Company name
             * @example Acme Corp
             */
            companyName: string;
        };
        LoginDto: {
            /**
             * @description User email address
             * @example jane@example.com
             */
            email: string;
            /**
             * @description Account password
             * @example supersecret123
             */
            password: string;
        };
        UpdateUserDto: {
            /**
             * @description New display name
             * @example Jane Smith
             */
            name?: string;
            /**
             * @description New email address
             * @example jane.smith@example.com
             */
            email?: string;
        };
        CreateWorkspaceDto: {
            /**
             * @description Human-readable workspace name
             * @example My Brand Assets
             */
            name: string;
        };
        CreateMetadataFieldDto: {
            /**
             * @description Group this field belongs to
             * @example uuid-of-group
             */
            groupId?: string;
            /**
             * @description Machine-readable field key (unique per workspace)
             * @example photographer
             */
            key: string;
            /**
             * @description Human-readable display label
             * @example Photographer Name
             */
            label: string;
            /**
             * @description Type of this metadata field
             * @example string
             * @enum {string}
             */
            fieldType: "string" | "text" | "integer" | "float" | "boolean" | "date" | "datetime" | "enum" | "multi_select" | "json" | "url" | "email" | "reference";
            /**
             * @description Options for enum/multi_select (choices array) or reference (target model)
             * @example {
             *       "choices": [
             *         "Nike",
             *         "Adidas",
             *         "Puma"
             *       ]
             *     }
             */
            options?: Record<string, never>;
            /**
             * @description Validation rules: min, max, pattern, required, choices
             * @example {
             *       "min": 0,
             *       "max": 1000000
             *     }
             */
            validationRules?: Record<string, never>;
            /**
             * @description Index this field for search
             * @default false
             */
            isSearchable: boolean;
            /**
             * @description Make this field required
             * @default false
             */
            isRequired: boolean;
            /**
             * @description Default value (type-agnostic)
             * @example Unknown
             */
            defaultValue?: Record<string, never>;
            /**
             * @description Display order within its group
             * @example 0
             */
            sortOrder?: number;
        };
        UpdateMetadataFieldDto: {
            /**
             * @description Group this field belongs to
             * @example uuid-of-group
             */
            groupId?: string;
            /**
             * @description Machine-readable field key (unique per workspace)
             * @example photographer
             */
            key?: string;
            /**
             * @description Human-readable display label
             * @example Photographer Name
             */
            label?: string;
            /**
             * @description Type of this metadata field
             * @example string
             * @enum {string}
             */
            fieldType?: "string" | "text" | "integer" | "float" | "boolean" | "date" | "datetime" | "enum" | "multi_select" | "json" | "url" | "email" | "reference";
            /**
             * @description Options for enum/multi_select (choices array) or reference (target model)
             * @example {
             *       "choices": [
             *         "Nike",
             *         "Adidas",
             *         "Puma"
             *       ]
             *     }
             */
            options?: Record<string, never>;
            /**
             * @description Validation rules: min, max, pattern, required, choices
             * @example {
             *       "min": 0,
             *       "max": 1000000
             *     }
             */
            validationRules?: Record<string, never>;
            /**
             * @description Index this field for search
             * @default false
             */
            isSearchable: boolean;
            /**
             * @description Make this field required
             * @default false
             */
            isRequired: boolean;
            /**
             * @description Default value (type-agnostic)
             * @example Unknown
             */
            defaultValue?: Record<string, never>;
            /**
             * @description Display order within its group
             * @example 0
             */
            sortOrder?: number;
        };
        CreateMetadataGroupDto: {
            /**
             * @description Group name
             * @example Photography Metadata
             */
            name: string;
            /**
             * @description Optional description shown in the UI
             * @example Camera, lens, and shoot settings
             */
            description?: string;
            /**
             * @description Display order (lower = first)
             * @example 1
             */
            sortOrder?: number;
        };
        CreateMetadataTemplateDto: {
            /**
             * @description Template name
             * @example Product Photography Template
             */
            name: string;
            /**
             * @description Template description
             * @example Standard fields for product shoot assets
             */
            description?: string;
            /**
             * @description Ordered list of MetadataFieldDefinition UUIDs in this template
             * @example [
             *       "uuid-1",
             *       "uuid-2",
             *       "uuid-3"
             *     ]
             */
            fieldIds: string[];
        };
        MetadataEntryDto: {
            /**
             * @description UUID of the MetadataFieldDefinition
             * @example uuid-of-field
             */
            fieldId: string;
            /**
             * @description Value to set — type must match the field type
             * @example Annie Leibovitz
             */
            value: Record<string, never>;
        };
        SetAssetMetadataDto: {
            /** @description Array of field ID + value pairs to upsert on this asset */
            entries: components["schemas"]["MetadataEntryDto"][];
        };
        BulkTagDto: {
            /**
             * @description Tag names to add or remove. Will be normalized (lowercase, trimmed).
             * @example [
             *       "summer_campaign",
             *       "product_launch",
             *       "hero-shot"
             *     ]
             */
            tags: string[];
        };
        IngestAiMetadataDto: {
            /**
             * @description AI provider name
             * @example google_vision
             */
            provider: string;
            /**
             * @description Model or API version used
             * @example v1p3beta1
             */
            modelVersion?: string;
            /**
             * @description Object detection or classification labels
             * @example [
             *       "dog",
             *       "outdoor",
             *       "park"
             *     ]
             */
            labels?: string[];
            /**
             * @description OCR-extracted text content
             * @example SALE 50% OFF
             */
            ocrText?: string;
            /**
             * @description Dominant color palette (hex codes)
             * @example [
             *       "#FF5733",
             *       "#1ABC9C"
             *     ]
             */
            colorPalette?: string[];
            /**
             * @description Scene classification tags
             * @example [
             *       "beach",
             *       "sunset",
             *       "travel"
             *     ]
             */
            sceneTags?: string[];
            /**
             * @description Confidence scores per label
             * @example {
             *       "dog": 0.98,
             *       "outdoor": 0.75
             *     }
             */
            confidenceScores?: Record<string, never>;
            /** @description Full raw provider response (preserved for reprocessing) */
            rawResponse?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully. Returns user object and JWT access token. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error – missing or invalid fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email is already in use. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful. Returns user object and JWT access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error – missing or invalid fields. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            /** @description Profile updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_listWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of workspaces returned successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_createWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceDto"];
            };
        };
        responses: {
            /** @description Workspace created successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_uploadFile: {
        parameters: {
            query?: {
                /** @description Set to `true` to skip duplicate detection and force upload */
                force?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description File to upload and workspace target */
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description The file to upload
                     */
                    file: string;
                    /**
                     * Format: uuid
                     * @description Target workspace UUID
                     * @example 550e8400-e29b-41d4-a716-446655440000
                     */
                    workspace_id: string;
                };
            };
        };
        responses: {
            /** @description Asset uploaded and stored successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid JWT token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User does not own the target workspace. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Workspace not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Duplicate detected. Response body contains `duplicate_type` (`exact` | `near`), `hammingDistance` (for near), and `existing_asset`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_listAssets: {
        parameters: {
            query: {
                workspace_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetsController_deleteAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchController_search: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReindexController_reindex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reindexing successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReindexController_reindexCustomer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reindexing successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataFieldsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of fields. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataFieldsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMetadataFieldDto"];
            };
        };
        responses: {
            /** @description Field created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A field with this key already exists. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataFieldsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                fieldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Field not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataFieldsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                fieldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Field not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataFieldsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                fieldId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMetadataFieldDto"];
            };
        };
        responses: {
            /** @description Field updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Field not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataGroupsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataGroupsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMetadataGroupDto"];
            };
        };
        responses: {
            /** @description Group created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataGroupsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                groupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Group not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataTemplatesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataTemplatesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMetadataTemplateDto"];
            };
        };
        responses: {
            /** @description Template created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataTemplatesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MetadataTemplatesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Template not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetMetadataController_getMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metadata values returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetMetadataController_setMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAssetMetadataDto"];
            };
        };
        responses: {
            /** @description Metadata updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error for one or more values. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset or field not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetMetadataController_applyTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Template applied. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Asset or template not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetMetadataController_getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version history returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AssetMetadataController_getFieldHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
                fieldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Field history returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_listWorkspaceTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag list returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_getAssetTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_addTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagDto"];
            };
        };
        responses: {
            /** @description Tags added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagsController_removeTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkTagDto"];
            };
        };
        responses: {
            /** @description Tags removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiMetadataController_getForAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AI metadata returned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiMetadataController_ingest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestAiMetadataDto"];
            };
        };
        responses: {
            /** @description AI metadata ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiMetadataController_getLatest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assetId: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest record from provider. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
